### ISSUE TITLE
'created_at' cannot be specified for SofortTransaction model form as it is a non-editable field

### ISSUE THREAD

**Issue by wh5a** [ParticulateSolutions/django-sofortueberweisung#6]
When clicking on any transactions from the admin, Django gives this error. Please see the following link for a fix

https://stackoverflow.com/questions/53989455/django-created-cannot-be-specified-for-order-model-form-as-it-is-a-non-editab

**Comment by willtho89** [comment]
@wh5a thank you for making us aware of this issue its fixed now with #7 
A new release 0.2.2 has been uploaded
